# Blog Configuration for GitHub Pages
title: "Developer Workflows & AI-Assisted Content"
description: "Comprehensive guides on developer tools, modern development environments, and AI-first content creation"
baseurl: ""
url: "https://garywu.github.io"
baseurl: "/blog"

# Build settings
markdown: kramdown
highlighter: rouge
theme: minima

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# Kramdown settings
kramdown:
  input: GFM
  syntax_highlighter: rouge

# Collections for blog posts
# collections:
#   posts:
#     output: true
#     permalink: /:collection/:name/

# Default layouts
defaults:
  - scope:
      path: ""
      type: "pages"
    values:
      layout: "page"
  - scope:
      path: "git-publish"
    values:
      layout: "page"
      category: "git-publish"
  - scope:
      path: "bootstrapping-setup"
    values:
      layout: "page"
      category: "bootstrapping-setup"
  - scope:
      path: "w-slash-ai"
    values:
      layout: "page"
      category: "w-slash-ai"

# Exclude from processing
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - .git/
  - .gitignore
  - "*/ai/"

# Site navigation
header_pages:
  - git-publish/README.md
  - bootstrapping-setup/README.md
  - w-slash-ai/README.md

# Author information
author:
  name: "Gary Wu"
  github: "garywu"

# SEO and social
twitter:
  username: garywu
  card: summary

social:
  name: Gary Wu
  links:
    - https://github.com/garywu

# Google Analytics (uncomment and add your tracking ID when ready)
# google_analytics: UA-XXXXXXXX-X 